# Generated by Django 5.1.2 on 2024-11-04 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spravki', models.IntegerField(blank=True, null=True, verbose_name='Справки')),
                ('post_cpgu', models.IntegerField(blank=True, null=True, verbose_name='Пост ЦПГУ')),
                ('treb_mil', models.IntegerField(blank=True, null=True, verbose_name='ТРЕБ МИЛ')),
                ('vlitiya_kart', models.IntegerField(blank=True, null=True, verbose_name='ВЛИТИЯ КАРТ')),
                ('aktual', models.IntegerField(blank=True, null=True, verbose_name='АКТУАЛ')),
                ('post_prekr', models.IntegerField(blank=True, null=True, verbose_name='ПОСТ ПРЕКР')),
                ('post_objavl', models.IntegerField(blank=True, null=True, verbose_name='ПОСТ ОБЬЯВЛ')),
                ('istreb', models.IntegerField(blank=True, null=True, verbose_name='ИСТРЕБОВАНИЕ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
