# Generated by Django 5.1.2 on 2024-11-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diogram_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='post_cpgu',
            field=models.IntegerField(blank=True, null=True, verbose_name='ПОСТ  ЦПГУ'),
        ),
    ]
